version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simple_blog_api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres